# Generated by Django 5.1.4 on 2025-05-27 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0014_remove_student_stud_card_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='locations/')),
                ('image_description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(default='building', max_length=50)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.admin')),
            ],
        ),
    ]
