# Generated by Django 5.1.4 on 2025-05-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campuslocation',
            name='image',
        ),
        migrations.AddField(
            model_name='campuslocation',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campuslocation',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='campuslocation',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
