# Generated by Django 5.1.4 on 2025-05-28 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_remove_campuslocation_image_campuslocation_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campuslocation',
            name='image_description',
        ),
    ]
