# Generated by Django 5.1.4 on 2025-03-11 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0004_alter_student_stud_card_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('image', models.ImageField(null=True, upload_to='event_images')),
                ('location', models.CharField(max_length=255)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.admin')),
            ],
        ),
    ]
