# Generated by Django 5.1.4 on 2025-04-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
