# Generated by Django 5.1.4 on 2025-05-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.BinaryField(default=0, editable=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default=''),
        ),
    ]
