# Generated by Django 5.1.4 on 2025-05-13 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_event_end_time_alter_event_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rsvp',
            old_name='guest_studentNumber',
            new_name='guest_studentnumber',
        ),
    ]
