# Generated by Django 5.1.4 on 2025-05-11 16:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0014_remove_student_stud_card_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Action',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('icon', models.CharField(max_length=255, null=True)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.admin')),
            ],
        ),
    ]
