# Generated by Django 5.1.4 on 2025-03-03 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('campus_id', models.IntegerField(primary_key=True, serialize=False)),
                ('campus_name', models.CharField(max_length=164)),
                ('location', models.CharField(max_length=164)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('campus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.campus')),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredStudent',
            fields=[
                ('studentNumber', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('campus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.campus')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentNumber', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('studentEmail', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('stud_card_image', models.ImageField(upload_to='images')),
                ('campus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.campus')),
            ],
        ),
    ]
