# Generated by Django 5.1.4 on 2025-03-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_student_name_student_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='contact',
            field=models.CharField(max_length=10),
        ),
    ]
