# Generated by Django 5.1.4 on 2025-03-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_admin_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stud_card_image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
