# Generated by Django 5.1.4 on 2025-03-31 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_student_stud_card_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campus',
            name='campus_id',
        ),
        migrations.AddField(
            model_name='campus',
            name='id',
            field=models.BigAutoField(auto_created=True,primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
