# Generated by Django 5.1.4 on 2025-03-31 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_remove_campus_campus_id_campus_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campus',
            name='id',
        ),
        migrations.AddField(
            model_name='campus',
            name='campus_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
