# Generated by Django 5.1.4 on 2025-03-31 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_alter_campus_campus_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='campus_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
