# Generated by Django 5.1.4 on 2025-05-02 14:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_alter_campus_campus_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='login_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
