# Generated by Django 5.1.4 on 2025-05-11 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_student_login_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='stud_card_image',
        ),
    ]
