# Generated by Django 5.1.4 on 2025-03-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_alter_bus_schedule_bus_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulecode',
            name='campus1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='schedulecode',
            name='campus2',
            field=models.CharField(default='', max_length=100),
        ),
    ]
