# Generated by Django 5.1.4 on 2025-04-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0003_schedulecode_campus1_schedulecode_campus2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='bus_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
