# Generated by Django 5.1.4 on 2025-05-04 09:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0004_alter_bus_bus_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus_Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('schedule_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.schedulecode')),
            ],
        ),
    ]
